name: reactamole
version: 0.1
synopsis: Functional Reactive Molecular Programming
description: Domain-specific language for molecular programming. Reactamole uses Functional Reactive Programming (FRP) arrow combinators for manipulation and composition of Chemical Reaction Networks (CRNs).
# See README at <https://github.com/digMP/haskell-reactamole#readme>
# maintainer: Simon Hengel <sol@typeful.net>
# homepage: https://github.com/digMP/haskell-reactamole#readme
# github: digMP/haskell-reactamole
# category: Bio, Reactivity, FRP, Molecular Programming, Chemistry, Embedded
# extra-source-files:
#   - CHANGELOG.md

ghc-options: -Wall

default-extensions:
  - GADTs

library:
  source-dirs: src
  exposed-modules:
    - Bio.Reactamole
    - Bio.Reactamole.Core
    - Bio.Reactamole.Bool
    - Bio.Reactamole.Arr
    - Bio.Reactamole.Real
    - Bio.Reactamole.Matlab
    - Bio.Reactamole.Export
    - Bio.Reactamole.ArrChoice
  dependencies:
    - base
    - containers
    - mtl
    - process
    - text

tests:
  reactamole-test:
    main:        Main.hs
    source-dirs: test
    dependencies:
    - base
    - reactamole
    - tasty
    - tasty-hunit
